FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python3 python3-dev python3-pip build-essential ninja-build
RUN pip3 install --upgrade pip meson
COPY . /repo
WORKDIR /repo
RUN pip3 install . --config-settings=setup-args="-Dpassphrase=fuzzpyconcrete"

FROM ubuntu:22.04 as package
COPY --from=builder /usr/local /usr/local
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y python3
