FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python python-dev build-essential

COPY . /repo
WORKDIR /repo
RUN python setup.py install < stdin

FROM ubuntu:20.04 as package
COPY --from=builder /usr/local/bin/pyconcrete /usr/local/bin/pyconcrete

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-dev
